var ardata = [
			  [//14
			   {judul:"Derby Milan",
					deskripsi:"deskripsi 1",
					harga:"harga 1",
					gambar1:'kaos1.png',
					gambar2:'orang1.jpg',
					bg:'white'},
			   {judul:"Formasi Arsenal 2003-2004",
					deskripsi:"deskripsi 2",
					harga:"harga 2",
					gambar1:'kaos2.png',
					gambar2:'orang2.jpg',
					bg:'white'},
			   {judul:"Messi Goal Celebration",
					deskripsi:"deskripsi 3",
					harga:"harga 3",
					gambar1:'kaos3.png',
					gambar2:'orang3.jpg',
					bg:'white'},
			   {judul:"Buffon Save",
					deskripsi:"deskripsi 4",
					harga:"harga 4",
					gambar1:'kaos4.png',
					gambar2:'orang4.jpg',
					bg:'white'},
			   {judul:"Gerrard Lompat",
					deskripsi:"deskripsi 5",
					harga:"harga 5",
					gambar1:'kaos5.png',
					gambar2:'orang5.jpg',
					bg:'white'},
			   {judul:"Cristiano Ronaldo Bicycle Kick",
					deskripsi:"deskripsi 6",
					harga:"harga 6",
					gambar1:'kaos6.png',
					gambar2:'orang6.jpg',
					bg:'white'},
			   {judul:"Cristiano Ronaldo Siu",
					deskripsi:"deskripsi 7",
					harga:"harga 7",
					gambar1:'kaos7.png',
					gambar2:'orang7.jpg',
					bg:'white'},
			   {judul:"King Of The Kings",
					deskripsi:"deskripsi 8",
					harga:"harga 8",
					gambar1:'kaos8.png',
					gambar2:'orang8.jpg',
					bg:'white'},
			   {judul:"Balotelli City Why Always Me",
					deskripsi:"deskripsi 9",
					harga:"harga 9",
					gambar1:'kaos9.png',
					gambar2:'orang9.jpg',
					bg:'white'},
			   {judul:"Treble Winner MU",
					deskripsi:"deskripsi 10",
					harga:"harga 10",
					gambar1:'kaos10.png',
					gambar2:'orang10.jpg',
					bg:'white'},
			   {judul:"Hand Of God Maradona",
					deskripsi:"deskripsi 11",
					harga:"harga 11",
					gambar1:'kaos11.png',
					gambar2:'orang11.jpg',
					bg:'white'},
			   {judul:"Marco Van Basten 1988 Volley",
					deskripsi:"deskripsi 12",
					harga:"harga 12",
					gambar1:'kaos12.png',
					gambar2:'orang12.jpg',
					bg:'white'},
			   {judul:"Ronaldo R9 IL PHENOMENON",
					deskripsi:"deskripsi 13",
					harga:"harga 13",
					gambar1:'kaos13.png',
					gambar2:'orang13.jpg',
					bg:'white'},
			   {judul:"Tandukan Zidane",
					deskripsi:"deskripsi 14",
					harga:"harga 14",
					gambar1:'kaos14.png',
					gambar2:'orang14.jpg',
					bg:'white'}
			  ],
  
			  [//31
			   {judul:"Florian Wirtz 1",
					deskripsi:"deskripsi 1",
					harga:"harga 1",
					gambar1:'kaos1.png',
					gambar2:'orang1.jpg',
					bg:'black'},
			   {judul:"Florian Wirtz 2",
					deskripsi:"deskripsi 2",
					harga:"harga 2",
					gambar1:'kaos2.png',
					gambar2:'orang2.jpg',
					bg:'white'},
			   {judul:"Florian Wirtz 3",
					deskripsi:"deskripsi 3",
					harga:"harga 3",
					gambar1:'kaos3.png',
					gambar2:'orang3.jpg',
					bg:'black'},
			   {judul:"Florian Wirtz 4",
					deskripsi:"deskripsi 4",
					harga:"harga 4",
					gambar1:'kaos4.png',
					gambar2:'orang4.jpg',
					bg:'white'},
			   {judul:"Jamal Musiala 1",
					deskripsi:"deskripsi 5",
					harga:"harga 5",
					gambar1:'kaos5.png',
					gambar2:'orang5.jpg',
					bg:'black'},
			   {judul:"Jamal Musiala 2",
					deskripsi:"deskripsi 6",
					harga:"harga 6",
					gambar1:'kaos6.png',
					gambar2:'orang6.jpg',
					bg:'white'},
			   {judul:"Jamal Musiala 3",
					deskripsi:"deskripsi 7",
					harga:"harga 7",
					gambar1:'kaos7.png',
					gambar2:'orang7.jpg',
					bg:'black'},
			   {judul:"Jamal Musiala 4",
					deskripsi:"deskripsi 8",
					harga:"harga 8",
					gambar1:'kaos8.png',
					gambar2:'orang8.jpg',
					bg:'white'},
			   {judul:"Jamal Musiala 5",
					deskripsi:"deskripsi 9",
					harga:"harga 9",
					gambar1:'kaos9.png',
					gambar2:'orang9.jpg',
					bg:'black'},
			   {judul:"Jamal Musiala 6",
					deskripsi:"deskripsi 10",
					harga:"harga 10",
					gambar1:'kaos10.png',
					gambar2:'orang10.jpg',
					bg:'white'},
			   {judul:"Lamine Yamal 1",
					deskripsi:"deskripsi 11",
					harga:"harga 11",
					gambar1:'kaos11.png',
					gambar2:'orang11.jpg',
					bg:'white'},
			   {judul:"Lamine Yamal 2",
					deskripsi:"deskripsi 12",
					harga:"harga 12",
					gambar1:'kaos12.png',
					gambar2:'orang12.jpg',
					bg:'white'},
			   {judul:"Lamine Yamal 3",
					deskripsi:"deskripsi 13",
					harga:"harga 13",
					gambar1:'kaos13.png',
					gambar2:'orang13.jpg',
					bg:'white'},
			   {judul:"Lamine Yamal 4",
					deskripsi:"deskripsi 14",
					harga:"harga 14",
					gambar1:'kaos14.png',
					gambar2:'orang14.jpg',
					bg:'white'},
			   {judul:"Nico Williams 1",
					deskripsi:"deskripsi 15",
					harga:"harga 15",
					gambar1:'kaos15.png',
					gambar2:'orang15.jpg',
					bg:'black'},
			   {judul:"Nico Williams 2",
					deskripsi:"deskripsi 16",
					harga:"harga 16",
					gambar1:'kaos16.png',
					gambar2:'orang16.jpg',
					bg:'white'},
			   {judul:"Vini Jr",
					deskripsi:"deskripsi 17",
					harga:"harga 17",
					gambar1:'kaos17.png',
					gambar2:'orang17.jpg',
					bg:'white'},
			   {judul:"Rodrygo",
					deskripsi:"deskripsi 18",
					harga:"harga 18",
					gambar1:'kaos18.png',
					gambar2:'orang18.jpg',
					bg:'white'},
			   {judul:"Bellingham",
					deskripsi:"deskripsi 19",
					harga:"harga 19",
					gambar1:'kaos19.png',
					gambar2:'orang19.jpg',
					bg:'white'},
			   {judul:"Mbappe",
					deskripsi:"deskripsi 20",
					harga:"harga 20",
					gambar1:'kaos20.png',
					gambar2:'orang20.jpg',
					bg:'white'},
			   {judul:"Ataque Real Madrid 1",
					deskripsi:"deskripsi 21",
					harga:"harga 21",
					gambar1:'kaos21.png',
					gambar2:'orang21.jpg',
					bg:'white'},
			   {judul:"Ataque Real Madrid 2",
					deskripsi:"deskripsi 22",
					harga:"harga 22",
					gambar1:'kaos22.png',
					gambar2:'orang22.jpg',
					bg:'white'},
			   {judul:"Ataque Real Madrid 3",
					deskripsi:"deskripsi 23",
					harga:"harga 23",
					gambar1:'kaos23.png',
					gambar2:'orang23.jpg',
					bg:'white'},
			   {judul:"Vini+Jude+Rodrygo 1",
					deskripsi:"deskripsi 24",
					harga:"harga 24",
					gambar1:'kaos24.png',
					gambar2:'orang24.jpg',
					bg:'white'},
			   {judul:"Vini+Jude+Rodrygo 2",
					deskripsi:"deskripsi 25",
					harga:"harga 25",
					gambar1:'kaos25.png',
					gambar2:'orang25.jpg',
					bg:'white'},
			   {judul:"Jude Bellingham 1",
					deskripsi:"deskripsi 26",
					harga:"harga 26",
					gambar1:'kaos26.png',
					gambar2:'orang26.jpg',
					bg:'white'},
			   {judul:"Jude Bellingham 2",
					deskripsi:"deskripsi 27",
					harga:"harga 27",
					gambar1:'kaos27.png',
					gambar2:'orang27.jpg',
					bg:'white'},
			   {judul:"Jude Bellingham 3",
					deskripsi:"deskripsi 28",
					harga:"harga 28",
					gambar1:'kaos28.png',
					gambar2:'orang28.jpg',
					bg:'white'},
			   {judul:"Jude Bellingham 4",
					deskripsi:"deskripsi 29",
					harga:"harga 29",
					gambar1:'kaos29.png',
					gambar2:'orang29.jpg',
					bg:'white'},
			   {judul:"Jude Bellingham 5",
					deskripsi:"deskripsi 30",
					harga:"harga 30",
					gambar1:'kaos30.png',
					gambar2:'orang30.jpg',
					bg:'white'},
			   {judul:"Arda Guler",
					deskripsi:"deskripsi 31",
					harga:"harga 31",
					gambar1:'kaos31.png',
					gambar2:'orang31.jpg',
					bg:'white'}
			  ],

			  
			  [//30
			   {judul:"Erling Haaland Manchester City 1",
					deskripsi:"deskripsi 1",
					harga:"harga 1",
					gambar1:'kaos1.png',
					gambar2:'orang1.jpg',
					bg:'black'},
			   {judul:"Erling Haaland Manchester City 2",
					deskripsi:"deskripsi 2",
					harga:"harga 2",
					gambar1:'kaos2.png',
					gambar2:'orang2.jpg',
					bg:'white'},
			   {judul:"Erling Haaland Manchester City 3",
					deskripsi:"deskripsi 3",
					harga:"harga 3",
					gambar1:'kaos3.png',
					gambar2:'orang3.jpg',
					bg:'black'},
			   {judul:"Erling Haaland Manchester City 4",
					deskripsi:"deskripsi 4",
					harga:"harga 4",
					gambar1:'kaos4.png',
					gambar2:'orang4.jpg',
					bg:'white'},
			   {judul:"Martin Odegaard Arsenal 1",
					deskripsi:"deskripsi 5",
					harga:"harga 5",
					gambar1:'kaos5.png',
					gambar2:'orang5.jpg',
					bg:'black'},
			   {judul:"Martin Odegaard Arsenal 2",
					deskripsi:"deskripsi 6",
					harga:"harga 6",
					gambar1:'kaos6.png',
					gambar2:'orang6.jpg',
					bg:'white'},
			   {judul:"Martin Odegaard Arsenal 3",
					deskripsi:"deskripsi 7",
					harga:"harga 7",
					gambar1:'kaos7.png',
					gambar2:'orang7.jpg',
					bg:'black'},
			   {judul:"Martin Odegaard Arsenal 4",
					deskripsi:"deskripsi 8",
					harga:"harga 8",
					gambar1:'kaos8.png',
					gambar2:'orang8.jpg',
					bg:'white'},
			   {judul:"Martin Odegaard Arsenal 5",
					deskripsi:"deskripsi 9",
					harga:"harga 9",
					gambar1:'kaos9.png',
					gambar2:'orang9.jpg',
					bg:'black'},
			   {judul:"Martin Odegaard Arsenal 6",
					deskripsi:"deskripsi 10",
					harga:"harga 10",
					gambar1:'kaos10.png',
					gambar2:'orang10.jpg',
					bg:'white'},
			   {judul:"Cole Palmer Chelsea 1",
					deskripsi:"deskripsi 11",
					harga:"harga 11",
					gambar1:'kaos11.png',
					gambar2:'orang11.jpg',
					bg:'black'},
			   {judul:"Cole Palmer Chelsea 2",
					deskripsi:"deskripsi 12",
					harga:"harga 12",
					gambar1:'kaos12.png',
					gambar2:'orang12.jpg',
					bg:'white'},
			   {judul:"Cole Palmer Chelsea 3",
					deskripsi:"deskripsi 13",
					harga:"harga 13",
					gambar1:'kaos13.png',
					gambar2:'orang13.jpg',
					bg:'black'},
			   {judul:"Cole Palmer Chelsea 4",
					deskripsi:"deskripsi 14",
					harga:"harga 14",
					gambar1:'kaos14.png',
					gambar2:'orang14.jpg',
					bg:'white'},
			   {judul:"Bukayo Saka Arsenal 1",
					deskripsi:"deskripsi 15",
					harga:"harga 15",
					gambar1:'kaos15.png',
					gambar2:'orang15.jpg',
					bg:'white'},
			   {judul:"Bukayo Saka Arsenal 2",
					deskripsi:"deskripsi 16",
					harga:"harga 16",
					gambar1:'kaos16.png',
					gambar2:'orang16.jpg',
					bg:'black'},
			   {judul:"Bukayo Saka Arsenal 3",
					deskripsi:"deskripsi 17",
					harga:"harga 17",
					gambar1:'kaos17.png',
					gambar2:'orang17.jpg',
					bg:'white'},
			   {judul:"Bukayo Saka Arsenal 4",
					deskripsi:"deskripsi 18",
					harga:"harga 18",
					gambar1:'kaos18.png',
					gambar2:'orang18.jpg',
					bg:'black'},
			   {judul:"Trend Alexander-Arnold Liverpool 1",
					deskripsi:"deskripsi 19",
					harga:"harga 19",
					gambar1:'kaos19.png',
					gambar2:'orang19.jpg',
					bg:'white'},
			   {judul:"Trend Alexander-Arnold Liverpool 2",
					deskripsi:"deskripsi 20",
					harga:"harga 20",
					gambar1:'kaos20.png',
					gambar2:'orang20.jpg',
					bg:'black'},
			   {judul:"Trend Alexander-Arnold Liverpool 3",
					deskripsi:"deskripsi 21",
					harga:"harga 21",
					gambar1:'kaos21.png',
					gambar2:'orang21.jpg',
					bg:'white'},
			   {judul:"Trend Alexander-Arnold Liverpool 4",
					deskripsi:"deskripsi 22",
					harga:"harga 22",
					gambar1:'kaos22.png',
					gambar2:'orang22.jpg',
					bg:'black'},
			   {judul:"Omari Hutchinson Ipswich Town 1",
					deskripsi:"deskripsi 23",
					harga:"harga 23",
					gambar1:'kaos23.png',
					gambar2:'orang23.jpg',
					bg:'white'},
			   {judul:"Omari Hutchinson Ipswich Town 2",
					deskripsi:"deskripsi 24",
					harga:"harga 24",
					gambar1:'kaos24.png',
					gambar2:'orang24.jpg',
					bg:'black'},
			   {judul:"Phil Foden 1",
					deskripsi:"deskripsi 25",
					harga:"harga 25",
					gambar1:'kaos25.png',
					gambar2:'orang25.jpg',
					bg:'white'},
			   {judul:"Phil Foden 2",
					deskripsi:"deskripsi 26",
					harga:"harga 26",
					gambar1:'kaos26.png',
					gambar2:'orang26.jpg',
					bg:'black'},
			   {judul:"Phil Foden 3",
					deskripsi:"deskripsi 27",
					harga:"harga 27",
					gambar1:'kaos27.png',
					gambar2:'orang27.jpg',
					bg:'white'},
			   {judul:"Phil Foden 4",
					deskripsi:"deskripsi 28",
					harga:"harga 28",
					gambar1:'kaos28.png',
					gambar2:'orang28.jpg',
					bg:'black'},
			   {judul:"Phil Foden 5",
					deskripsi:"deskripsi 29",
					harga:"harga 29",
					gambar1:'kaos29.png',
					gambar2:'orang29.jpg',
					bg:'white'},
			   {judul:"Phil Foden 6",
					deskripsi:"deskripsi 30",
					harga:"harga 30",
					gambar1:'kaos30.png',
					gambar2:'orang30.jpg',
					bg:'black'}
			  ],
		  
		  
			  [//70
			   {judul:"Rafael Struick 1",
					deskripsi:"deskripsi 1",
					harga:"harga 1",
					gambar1:'kaos1.png',
					gambar2:'orang1.jpg',
					bg:'white'},
			   {judul:"Rafael Struick 2",
					deskripsi:"deskripsi 2",
					harga:"harga 2",
					gambar1:'kaos2.png',
					gambar2:'orang2.jpg',
					bg:'black'},
			   {judul:"Rafael Struick 3",
					deskripsi:"deskripsi 3",
					harga:"harga 3",
					gambar1:'kaos3.png',
					gambar2:'orang3.jpg',
					bg:'white'},
			   {judul:"Rafael Struick 4",
					deskripsi:"deskripsi 4",
					harga:"harga 4",
					gambar1:'kaos4.png',
					gambar2:'orang4.jpg',
					bg:'black'},
			   {judul:"Rafael Struick 5",
					deskripsi:"deskripsi 5",
					harga:"harga 5",
					gambar1:'kaos5.png',
					gambar2:'orang5.jpg',
					bg:'white'},
			   {judul:"Rafael Struick 6",
					deskripsi:"deskripsi 6",
					harga:"harga 6",
					gambar1:'kaos6.png',
					gambar2:'orang6.jpg',
					bg:'black'},
			   {judul:"Rafael Struick 7",
					deskripsi:"deskripsi 7",
					harga:"harga 7",
					gambar1:'kaos7.png',
					gambar2:'orang7.jpg',
					bg:'white'},
			   {judul:"Rafael Struick 8",
					deskripsi:"deskripsi 8",
					harga:"harga 8",
					gambar1:'kaos8.png',
					gambar2:'orang8.jpg',
					bg:'black'},
			   {judul:"Rafael Struick 9",
					deskripsi:"deskripsi 9",
					harga:"harga 9",
					gambar1:'kaos9.png',
					gambar2:'orang9.jpg',
					bg:'white'},
			   {judul:"Rafael Struick 10",
					deskripsi:"deskripsi 10",
					harga:"harga 10",
					gambar1:'kaos10.png',
					gambar2:'orang10.jpg',
					bg:'black'},
			   {judul:"Rafael Struick 11",
					deskripsi:"deskripsi 11",
					harga:"harga 11",
					gambar1:'kaos11.png',
					gambar2:'orang11.jpg',
					bg:'white'},
			   {judul:"Rafael Struick 12",
					deskripsi:"deskripsi 12",
					harga:"harga 12",
					gambar1:'kaos12.png',
					gambar2:'orang12.jpg',
					bg:'black'},
			   {judul:"Rafael Struick 13",
					deskripsi:"deskripsi 13",
					harga:"harga 13",
					gambar1:'kaos13.png',
					gambar2:'orang13.jpg',
					bg:'white'},
			   {judul:"Rafael Struick 14",
					deskripsi:"deskripsi 14",
					harga:"harga 14",
					gambar1:'kaos14.png',
					gambar2:'orang14.jpg',
					bg:'black'},
			   {judul:"Thom Haye 1",
					deskripsi:"deskripsi 15",
					harga:"harga 15",
					gambar1:'kaos15.png',
					gambar2:'orang15.jpg',
					bg:'white'},
			   {judul:"Thom Haye 2",
					deskripsi:"deskripsi 16",
					harga:"harga 16",
					gambar1:'kaos16.png',
					gambar2:'orang16.jpg',
					bg:'black'},
			   {judul:"Thom Haye 3",
					deskripsi:"deskripsi 17",
					harga:"harga 17",
					gambar1:'kaos17.png',
					gambar2:'orang17.jpg',
					bg:'white'},
			   {judul:"Thom Haye 4",
					deskripsi:"deskripsi 18",
					harga:"harga 18",
					gambar1:'kaos18.png',
					gambar2:'orang18.jpg',
					bg:'black'},
			   {judul:"Thom Haye 5",
					deskripsi:"deskripsi 19",
					harga:"harga 19",
					gambar1:'kaos19.png',
					gambar2:'orang19.jpg',
					bg:'white'},
			   {judul:"Thom Haye 6",
					deskripsi:"deskripsi 20",
					harga:"harga 20",
					gambar1:'kaos20.png',
					gambar2:'orang20.jpg',
					bg:'black'},
			   {judul:"Thom Haye 7",
					deskripsi:"deskripsi 21",
					harga:"harga 21",
					gambar1:'kaos21.png',
					gambar2:'orang21.jpg',
					bg:'white'},
			   {judul:"Thom Haye 8",
					deskripsi:"deskripsi 22",
					harga:"harga 22",
					gambar1:'kaos22.png',
					gambar2:'orang22.jpg',
					bg:'black'},
			   {judul:"Ragnar Oratmangoen 1",
					deskripsi:"deskripsi 23",
					harga:"harga 23",
					gambar1:'kaos23.png',
					gambar2:'orang23.jpg',
					bg:'white'},
			   {judul:"Ragnar Oratmangoen 2",
					deskripsi:"deskripsi 24",
					harga:"harga 24",
					gambar1:'kaos24.png',
					gambar2:'orang24.jpg',
					bg:'black'},
			   {judul:"Jay Idzes 1",
					deskripsi:"deskripsi 25",
					harga:"harga 25",
					gambar1:'kaos25.png',
					gambar2:'orang25.jpg',
					bg:'white'},
			   {judul:"Jay Idzes 2",
					deskripsi:"deskripsi 26",
					harga:"harga 26",
					gambar1:'kaos26.png',
					gambar2:'orang26.jpg',
					bg:'white'},
			   {judul:"Jay Idzes 3",
					deskripsi:"deskripsi 27",
					harga:"harga 27",
					gambar1:'kaos27.png',
					gambar2:'orang27.jpg',
					bg:'black'},
			   {judul:"Jay Idzes 4",
					deskripsi:"deskripsi 28",
					harga:"harga 28",
					gambar1:'kaos28.png',
					gambar2:'orang28.jpg',
					bg:'black'},
			   {judul:"Maarten Paes 1",
					deskripsi:"deskripsi 29",
					harga:"harga 29",
					gambar1:'kaos29.png',
					gambar2:'orang29.jpg',
					bg:'white'},
			   {judul:"Maarten Paes 2",
					deskripsi:"deskripsi 30",
					harga:"harga 30",
					gambar1:'kaos30.png',
					gambar2:'orang30.jpg',
					bg:'black'},
			   {judul:"Maarten Paes 3",
					deskripsi:"deskripsi 31",
					harga:"harga 31",
					gambar1:'kaos31.png',
					gambar2:'orang31.jpg',
					bg:'white'},
			   {judul:"Maarten Paes 4",
					deskripsi:"deskripsi 32",
					harga:"harga 32",
					gambar1:'kaos32.png',
					gambar2:'orang32.jpg',
					bg:'black'},
			   {judul:"Marc Klok 1",
					deskripsi:"deskripsi 33",
					harga:"harga 33",
					gambar1:'kaos33.png',
					gambar2:'orang33.jpg',
					bg:'white'},
			   {judul:"Marc Klok 2",
					deskripsi:"deskripsi 34",
					harga:"harga 34",
					gambar1:'kaos34.png',
					gambar2:'orang34.jpg',
					bg:'black'},
			   {judul:"Marcelino 1",
					deskripsi:"deskripsi 35",
					harga:"harga 35",
					gambar1:'kaos35.png',
					gambar2:'orang35.jpg',
					bg:'white'},
			   {judul:"Marcelino 2",
					deskripsi:"deskripsi 36",
					harga:"harga 36",
					gambar1:'kaos36.png',
					gambar2:'orang36.jpg',
					bg:'black'},
			   {judul:"Marcelino 3",
					deskripsi:"deskripsi 37",
					harga:"harga 37",
					gambar1:'kaos37.png',
					gambar2:'orang37.jpg',
					bg:'white'},
			   {judul:"Marcelino 4",
					deskripsi:"deskripsi 38",
					harga:"harga 38",
					gambar1:'kaos38.png',
					gambar2:'orang38.jpg',
					bg:'black'},
			   {judul:"Justin Hubner 1",
					deskripsi:"deskripsi 39",
					harga:"harga 39",
					gambar1:'kaos39.png',
					gambar2:'orang39.jpg',
					bg:'white'},
			   {judul:"Justin Hubner 2",
					deskripsi:"deskripsi 40",
					harga:"harga 40",
					gambar1:'kaos40.png',
					gambar2:'orang40.jpg',
					bg:'black'},
			   {judul:"Justin Hubner 3",
					deskripsi:"deskripsi 41",
					harga:"harga 41",
					gambar1:'kaos41.png',
					gambar2:'orang41.jpg',
					bg:'white'},
			   {judul:"Justin Hubner 4",
					deskripsi:"deskripsi 42",
					harga:"harga 42",
					gambar1:'kaos42.png',
					gambar2:'orang42.jpg',
					bg:'black'},
			   {judul:"Calvin Verdonk 1",
					deskripsi:"deskripsi 43",
					harga:"harga 43",
					gambar1:'kaos43.png',
					gambar2:'orang43.jpg',
					bg:'white'},
			   {judul:"Calvin Verdonk 2",
					deskripsi:"deskripsi 44",
					harga:"harga 44",
					gambar1:'kaos44.png',
					gambar2:'orang44.jpg',
					bg:'black'},
			   {judul:"Calvin Verdonk 3",
					deskripsi:"deskripsi 45",
					harga:"harga 45",
					gambar1:'kaos45.png',
					gambar2:'orang45.jpg',
					bg:'white'},
			   {judul:"Calvin Verdonk 4",
					deskripsi:"deskripsi 46",
					harga:"harga 46",
					gambar1:'kaos46.png',
					gambar2:'orang46.jpg',
					bg:'black'},
			   {judul:"Calvin Verdonk 5",
					deskripsi:"deskripsi 47",
					harga:"harga 47",
					gambar1:'kaos47.png',
					gambar2:'orang47.jpg',
					bg:'white'},
			   {judul:"Calvin Verdonk 6",
					deskripsi:"deskripsi 48",
					harga:"harga 48",
					gambar1:'kaos48.png',
					gambar2:'orang48.jpg',
					bg:'black'},
			   {judul:"Calvin Verdonk 7",
					deskripsi:"deskripsi 49",
					harga:"harga 49",
					gambar1:'kaos49.png',
					gambar2:'orang49.jpg',
					bg:'white'},
			   {judul:"Calvin Verdonk 8",
					deskripsi:"deskripsi 50",
					harga:"harga 50",
					gambar1:'kaos50.png',
					gambar2:'orang50.jpg',
					bg:'black'},
			   {judul:"Shin Tae Yong 1",
					deskripsi:"deskripsi 51",
					harga:"harga 51",
					gambar1:'kaos51.png',
					gambar2:'orang51.jpg',
					bg:'white'},
			   {judul:"Shin Tae Yong 2",
					deskripsi:"deskripsi 52",
					harga:"harga 52",
					gambar1:'kaos52.png',
					gambar2:'orang52.jpg',
					bg:'black'},
			   {judul:"Shin Tae Yong 3",
					deskripsi:"deskripsi 53",
					harga:"harga 53",
					gambar1:'kaos53.png',
					gambar2:'orang53.jpg',
					bg:'white'},
			   {judul:"Shin Tae Yong 4",
					deskripsi:"deskripsi 54",
					harga:"harga 54",
					gambar1:'kaos54.png',
					gambar2:'orang54.jpg',
					bg:'black'},
			   {judul:"Rizky Ridho 1",
					deskripsi:"deskripsi 55",
					harga:"harga 55",
					gambar1:'kaos55.png',
					gambar2:'orang55.jpg',
					bg:'white'},
			   {judul:"Rizky Ridho 2",
					deskripsi:"deskripsi 56",
					harga:"harga 56",
					gambar1:'kaos56.png',
					gambar2:'orang56.jpg',
					bg:'black'},
			   {judul:"Rizky Ridho 3",
					deskripsi:"deskripsi 57",
					harga:"harga 57",
					gambar1:'kaos57.png',
					gambar2:'orang57.jpg',
					bg:'white'},
			   {judul:"Rizky Ridho 4",
					deskripsi:"deskripsi 58",
					harga:"harga 58",
					gambar1:'kaos58.png',
					gambar2:'orang58.jpg',
					bg:'black'},
			   {judul:"Nathan Tjoe-A-On 1",
					deskripsi:"deskripsi 59",
					harga:"harga 59",
					gambar1:'kaos59.png',
					gambar2:'orang59.jpg',
					bg:'white'},
			   {judul:"Nathan Tjoe-A-On 2",
					deskripsi:"deskripsi 60",
					harga:"harga 60",
					gambar1:'kaos60.png',
					gambar2:'orang60.jpg',
					bg:'black'},
			   {judul:"Nathan Tjoe-A-On 3",
					deskripsi:"deskripsi 61",
					harga:"harga 61",
					gambar1:'kaos61.png',
					gambar2:'orang61.jpg',
					bg:'white'},
			   {judul:"Nathan Tjoe-A-On 4",
					deskripsi:"deskripsi 62",
					harga:"harga 62",
					gambar1:'kaos62.png',
					gambar2:'orangv2.jpg',
					bg:'black'},
			   {judul:"Ivan Jenner 1",
					deskripsi:"deskripsi 63",
					harga:"harga 63",
					gambar1:'kaos63.png',
					gambar2:'orang63.jpg',
					bg:'white'},
			   {judul:"Ivan Jenner 2",
					deskripsi:"deskripsi 64",
					harga:"harga 64",
					gambar1:'kaos64.png',
					gambar2:'orang64.jpg',
					bg:'black'},
			   {judul:"Ivan Jenner 3",
					deskripsi:"deskripsi 65",
					harga:"harga 65",
					gambar1:'kaos65.png',
					gambar2:'orang65.jpg',
					bg:'white'},
			   {judul:"Ivan Jenner 4",
					deskripsi:"deskripsi 66",
					harga:"harga 66",
					gambar1:'kaos66.png',
					gambar2:'orang66.jpg',
					bg:'black'},
			   {judul:"Mees Hilgers 1",
					deskripsi:"deskripsi 67",
					harga:"harga 67",
					gambar1:'kaos67.png',
					gambar2:'orang67.jpg',
					bg:'white'},
			   {judul:"Mees Hilgers 2",
					deskripsi:"deskripsi 68",
					harga:"harga 68",
					gambar1:'kaos68.png',
					gambar2:'orang68.jpg',
					bg:'black'},
			   {judul:"Mees Hilgers 3",
					deskripsi:"deskripsi 69",
					harga:"harga 69",
					gambar1:'kaos69.png',
					gambar2:'orang69.jpg',
					bg:'white'},
			   {judul:"Mees Hilgers 4",
					deskripsi:"deskripsi 70",
					harga:"harga 70",
					gambar1:'kaos70.png',
					gambar2:'orang70.jpg',
					bg:'black'}
			  ],

	  
			  [//26
			   {judul:"AC Milan 1",
					deskripsi:"deskripsi 1",
					harga:"harga 1",
					gambar1:'kaos1.png',
					gambar2:'orang1.jpg',
					bg:'white'},
			   {judul:"AC Milan 2",
					deskripsi:"deskripsi 2",
					harga:"harga 2",
					gambar1:'kaos2.png',
					gambar2:'orang2.jpg',
					bg:'white'},
			   {judul:"AC Milan 3",
					deskripsi:"deskripsi 3",
					harga:"harga 3",
					gambar1:'kaos3.png',
					gambar2:'orang3.jpg',
					bg:'white'},
			   {judul:"AC Milan 4",
					deskripsi:"deskripsi 4",
					harga:"harga 4",
					gambar1:'kaos4.png',
					gambar2:'orang4.jpg',
					bg:'white'},
			   {judul:"Arsenal 1",
					deskripsi:"deskripsi 5",
					harga:"harga 5",
					gambar1:'kaos5.png',
					gambar2:'orang5.jpg',
					bg:'white'},
			   {judul:"Barcelona 1",
					deskripsi:"deskripsi 6",
					harga:"harga 6",
					gambar1:'kaos6.png',
					gambar2:'orang6.jpg',
					bg:'white'},
			   {judul:"Barcelona 2",
					deskripsi:"deskripsi 7",
					harga:"harga 7",
					gambar1:'kaos7.png',
					gambar2:'orang7.jpg',
					bg:'white'},
			   {judul:"Barcelona 3",
					deskripsi:"deskripsi 8",
					harga:"harga 8",
					gambar1:'kaos8.png',
					gambar2:'orang8.jpg',
					bg:'white'},
			   {judul:"Bayern Munchen 1",
					deskripsi:"deskripsi 9",
					harga:"harga 9",
					gambar1:'kaos9.png',
					gambar2:'orang9.jpg',
					bg:'white'},
			   {judul:"Chelsea 1",
					deskripsi:"deskripsi 10",
					harga:"harga 10",
					gambar1:'kaos10.png',
					gambar2:'orang10.jpg',
					bg:'white'},
			   {judul:"Chelsea 2",
					deskripsi:"deskripsi 11",
					harga:"harga 11",
					gambar1:'kaos11.png',
					gambar2:'orang11.jpg',
					bg:'white'},
			   {judul:"Chelsea 3",
					deskripsi:"deskripsi 12",
					harga:"harga 12",
					gambar1:'kaos12.png',
					gambar2:'orang12.jpg',
					bg:'white'},
			   {judul:"Chelsea 4",
					deskripsi:"deskripsi 13",
					harga:"harga 13",
					gambar1:'kaos13.png',
					gambar2:'orang13.jpg',
					bg:'white'},
			   {judul:"Juventus 1",
					deskripsi:"deskripsi 14",
					harga:"harga 14",
					gambar1:'kaos14.png',
					gambar2:'orang14.jpg',
					bg:'white'},
			   {judul:"Juventus 2",
					deskripsi:"deskripsi 15",
					harga:"harga 15",
					gambar1:'kaos15.png',
					gambar2:'orang15.jpg',
					bg:'white'},
			   {judul:"Liverpool 1",
					deskripsi:"deskripsi 16",
					harga:"harga 16",
					gambar1:'kaos16.png',
					gambar2:'orang16.jpg',
					bg:'white'},
			   {judul:"Liverpool 2",
					deskripsi:"deskripsi 17",
					harga:"harga 17",
					gambar1:'kaos17.png',
					gambar2:'orang17.jpg',
					bg:'white'},
			   {judul:"Liverpool 3",
					deskripsi:"deskripsi 18",
					harga:"harga 18",
					gambar1:'kaos18.png',
					gambar2:'orang18.jpg',
					bg:'white'},
			   {judul:"Liverpool 4",
					deskripsi:"deskripsi 19",
					harga:"harga 19",
					gambar1:'kaos19.png',
					gambar2:'orang19.jpg',
					bg:'white'},
			   {judul:"Manchester City 1",
					deskripsi:"deskripsi 20",
					harga:"harga 20",
					gambar1:'kaos20.png',
					gambar2:'orang20.jpg',
					bg:'white'},
			   {judul:"Manchester United 1",
					deskripsi:"deskripsi 21",
					harga:"harga 21",
					gambar1:'kaos21.png',
					gambar2:'orang21.jpg',
					bg:'white'},
			   {judul:"Manchester United 2",
					deskripsi:"deskripsi 22",
					harga:"harga 22",
					gambar1:'kaos22.png',
					gambar2:'orang22.jpg',
					bg:'white'},
			   {judul:"Manchester United 3",
					deskripsi:"deskripsi 23",
					harga:"harga 23",
					gambar1:'kaos23.png',
					gambar2:'orang23.jpg',
					bg:'white'},
			   {judul:"PSG 1",
					deskripsi:"deskripsi 24",
					harga:"harga 24",
					gambar1:'kaos24.png',
					gambar2:'orang24.jpg',
					bg:'white'},
			   {judul:"PSG 2",
					deskripsi:"deskripsi 25",
					harga:"harga 25",
					gambar1:'kaos25.png',
					gambar2:'orang25.jpg',
					bg:'white'},
			   {judul:"Real Madrid 1",
					deskripsi:"deskripsi 26",
					harga:"harga 26",
					gambar1:'kaos26.png',
					gambar2:'orang26.jpg',
					bg:'white'}
			  ],

			  
			  [//106
			   {judul:"judul 1",
					deskripsi:"deskripsi 1",
					harga:"harga 1",
					gambar1:'kaos1.jpg',
					gambar2:'orang1.jpg',
					bg:'white'},
			   {judul:"judul 2",
					deskripsi:"deskripsi 2",
					harga:"harga 2",
					gambar1:'kaos2.jpg',
					gambar2:'orang2.jpg',
					bg:'white'},
			   {judul:"judul 3",
					deskripsi:"deskripsi 3",
					harga:"harga 3",
					gambar1:'kaos3.jpg',
					gambar2:'orang3.jpg',
					bg:'white'},
			   {judul:"judul 4",
					deskripsi:"deskripsi 4",
					harga:"harga 4",
					gambar1:'kaos4.jpg',
					gambar2:'orang4.jpg',
					bg:'white'},
			   {judul:"judul 5",
					deskripsi:"deskripsi 5",
					harga:"harga 5",
					gambar1:'kaos5.jpg',
					gambar2:'orang5.jpg',
					bg:'white'},
			   {judul:"judul 6",
					deskripsi:"deskripsi 6",
					harga:"harga 6",
					gambar1:'kaos6.jpg',
					gambar2:'orang6.jpg',
					bg:'white'},
			   {judul:"judul 7",
					deskripsi:"deskripsi 7",
					harga:"harga 7",
					gambar1:'kaos7.jpg',
					gambar2:'orang7.jpg',
					bg:'white'},
			   {judul:"judul 8",
					deskripsi:"deskripsi 8",
					harga:"harga 8",
					gambar1:'kaos8.jpg',
					gambar2:'orang8.jpg',
					bg:'white'},
			   {judul:"judul 9",
					deskripsi:"deskripsi 9",
					harga:"harga 9",
					gambar1:'kaos9.jpg',
					gambar2:'orang9.jpg',
					bg:'white'},
			   {judul:"judul 10",
					deskripsi:"deskripsi 10",
					harga:"harga 10",
					gambar1:'kaos10.jpg',
					gambar2:'orang10.jpg',
					bg:'white'},
			   {judul:"judul 11",
					deskripsi:"deskripsi 11",
					harga:"harga 11",
					gambar1:'kaos11.jpg',
					gambar2:'orang11.jpg',
					bg:'white'},
			   {judul:"judul 12",
					deskripsi:"deskripsi 12",
					harga:"harga 12",
					gambar1:'kaos12.jpg',
					gambar2:'orang12.jpg',
					bg:'white'},
			   {judul:"judul 13",
					deskripsi:"deskripsi 13",
					harga:"harga 13",
					gambar1:'kaos13.jpg',
					gambar2:'orang13.jpg',
					bg:'white'},
			   {judul:"judul 14",
					deskripsi:"deskripsi 14",
					harga:"harga 14",
					gambar1:'kaos14.jpg',
					gambar2:'orang14.jpg',
					bg:'white'},
			   {judul:"judul 15",
					deskripsi:"deskripsi 15",
					harga:"harga 15",
					gambar1:'kaos15.jpg',
					gambar2:'orang15.jpg',
					bg:'white'},
			   {judul:"judul 16",
					deskripsi:"deskripsi 16",
					harga:"harga 16",
					gambar1:'kaos16.jpg',
					gambar2:'orang16.jpg',
					bg:'white'},
			   {judul:"judul 17",
					deskripsi:"deskripsi 17",
					harga:"harga 17",
					gambar1:'kaos17.jpg',
					gambar2:'orang17.jpg',
					bg:'white'},
			   {judul:"judul 18",
					deskripsi:"deskripsi 18",
					harga:"harga 18",
					gambar1:'kaos18.jpg',
					gambar2:'orang18.jpg',
					bg:'white'},
			   {judul:"judul 19",
					deskripsi:"deskripsi 19",
					harga:"harga 19",
					gambar1:'kaos19.jpg',
					gambar2:'orang19.jpg',
					bg:'white'},
			   {judul:"judul 20",
					deskripsi:"deskripsi 20",
					harga:"harga 20",
					gambar1:'kaos20.jpg',
					gambar2:'orang20.jpg',
					bg:'white'},
			   {judul:"judul 21",
					deskripsi:"deskripsi 21",
					harga:"harga 21",
					gambar1:'kaos21.jpg',
					gambar2:'orang21.jpg',
					bg:'white'},
			   {judul:"judul 22",
					deskripsi:"deskripsi 22",
					harga:"harga 22",
					gambar1:'kaos22.jpg',
					gambar2:'orang22.jpg',
					bg:'white'},
			   {judul:"judul 23",
					deskripsi:"deskripsi 23",
					harga:"harga 23",
					gambar1:'kaos23.jpg',
					gambar2:'orang23.jpg',
					bg:'white'},
			   {judul:"judul 24",
					deskripsi:"deskripsi 24",
					harga:"harga 24",
					gambar1:'kaos24.jpg',
					gambar2:'orang24.jpg',
					bg:'white'},
			   {judul:"judul 25",
					deskripsi:"deskripsi 25",
					harga:"harga 25",
					gambar1:'kaos25.jpg',
					gambar2:'orang25.jpg',
					bg:'white'},
			   {judul:"judul 26",
					deskripsi:"deskripsi 26",
					harga:"harga 26",
					gambar1:'kaos26.jpg',
					gambar2:'orang26.jpg',
					bg:'white'},
			   {judul:"judul 27",
					deskripsi:"deskripsi 27",
					harga:"harga 27",
					gambar1:'kaos27.jpg',
					gambar2:'orang27.jpg',
					bg:'white'},
			   {judul:"judul 28",
					deskripsi:"deskripsi 28",
					harga:"harga 28",
					gambar1:'kaos28.jpg',
					gambar2:'orang28.jpg',
					bg:'white'},
			   {judul:"judul 29",
					deskripsi:"deskripsi 29",
					harga:"harga 29",
					gambar1:'kaos29.jpg',
					gambar2:'orang29.jpg',
					bg:'white'},
			   {judul:"judul 30",
					deskripsi:"deskripsi 30",
					harga:"harga 30",
					gambar1:'kaos30.jpg',
					gambar2:'orang30.jpg',
					bg:'white'},
			   {judul:"judul 31",
					deskripsi:"deskripsi 31",
					harga:"harga 31",
					gambar1:'kaos31.jpg',
					gambar2:'orang31.jpg',
					bg:'white'},
			   {judul:"judul 32",
					deskripsi:"deskripsi 32",
					harga:"harga 32",
					gambar1:'kaos32.jpg',
					gambar2:'orang32.jpg',
					bg:'white'},
			   {judul:"judul 33",
					deskripsi:"deskripsi 33",
					harga:"harga 33",
					gambar1:'kaos33.jpg',
					gambar2:'orang33.jpg',
					bg:'white'},
			   {judul:"judul 34",
					deskripsi:"deskripsi 34",
					harga:"harga 34",
					gambar1:'kaos34.jpg',
					gambar2:'orang34.jpg',
					bg:'white'},
			   {judul:"judul 35",
					deskripsi:"deskripsi 35",
					harga:"harga 35",
					gambar1:'kaos35.jpg',
					gambar2:'orang35.jpg',
					bg:'white'},
			   {judul:"judul 36",
					deskripsi:"deskripsi 36",
					harga:"harga 36",
					gambar1:'kaos36.jpg',
					gambar2:'orang36.jpg',
					bg:'white'},
			   {judul:"judul 37",
					deskripsi:"deskripsi 37",
					harga:"harga 37",
					gambar1:'kaos37.jpg',
					gambar2:'orang37.jpg',
					bg:'white'},
			   {judul:"judul 38",
					deskripsi:"deskripsi 38",
					harga:"harga 38",
					gambar1:'kaos38.jpg',
					gambar2:'orang38.jpg',
					bg:'white'},
			   {judul:"judul 39",
					deskripsi:"deskripsi 39",
					harga:"harga 39",
					gambar1:'kaos39.jpg',
					gambar2:'orang39.jpg',
					bg:'white'},
			   {judul:"judul 40",
					deskripsi:"deskripsi 40",
					harga:"harga 40",
					gambar1:'kaos40.jpg',
					gambar2:'orang40.jpg',
					bg:'white'},
			   {judul:"judul 41",
					deskripsi:"deskripsi 41",
					harga:"harga 41",
					gambar1:'kaos41.jpg',
					gambar2:'orang41.jpg',
					bg:'white'},
			   {judul:"judul 42",
					deskripsi:"deskripsi 42",
					harga:"harga 42",
					gambar1:'kaos42.jpg',
					gambar2:'orang42.jpg',
					bg:'white'},
			   {judul:"judul 43",
					deskripsi:"deskripsi 43",
					harga:"harga 43",
					gambar1:'kaos43.jpg',
					gambar2:'orang43.jpg',
					bg:'white'},
			   {judul:"judul 44",
					deskripsi:"deskripsi 44",
					harga:"harga 44",
					gambar1:'kaos44.jpg',
					gambar2:'orang44.jpg',
					bg:'white'},
			   {judul:"judul 45",
					deskripsi:"deskripsi 45",
					harga:"harga 45",
					gambar1:'kaos45.jpg',
					gambar2:'orang45.jpg',
					bg:'white'},
			   {judul:"judul 46",
					deskripsi:"deskripsi 46",
					harga:"harga 46",
					gambar1:'kaos46.jpg',
					gambar2:'orang46.jpg',
					bg:'white'},
			   {judul:"judul 47",
					deskripsi:"deskripsi 47",
					harga:"harga 47",
					gambar1:'kaos47.jpg',
					gambar2:'orang47.jpg',
					bg:'white'},
			   {judul:"judul 48",
					deskripsi:"deskripsi 48",
					harga:"harga 48",
					gambar1:'kaos48.jpg',
					gambar2:'orang48.jpg',
					bg:'white'},
			   {judul:"judul 49",
					deskripsi:"deskripsi 49",
					harga:"harga 49",
					gambar1:'kaos49.jpg',gambar2:'orang49.jpg',
					bg:'white'},
			   {judul:"judul 50",
					deskripsi:"deskripsi 50",
					harga:"harga 50",
					gambar1:'kaos50.jpg',
					gambar2:'orang50.jpg',
					bg:'white'},
			   {judul:"judul 51",
					deskripsi:"deskripsi 51",
					harga:"harga 51",
					gambar1:'kaos51.jpg',
					gambar2:'orang51.jpg',
					bg:'white'},
			   {judul:"judul 52",
					deskripsi:"deskripsi 52",
					harga:"harga 52",
					gambar1:'kaos52.jpg',
					gambar2:'orang52.jpg',
					bg:'white'},
			   {judul:"judul 53",
					deskripsi:"deskripsi 53",
					harga:"harga 53",
					gambar1:'kaos53.jpg',
					gambar2:'orang53.jpg',
					bg:'white'},
			   {judul:"judul 54",
					deskripsi:"deskripsi 54",
					harga:"harga 54",
					gambar1:'kaos54.jpg',
					gambar2:'orang54.jpg',
					bg:'white'},
			   {judul:"judul 55",
					deskripsi:"deskripsi 55",
					harga:"harga 55",
					gambar1:'kaos55.jpg',
					gambar2:'orang55.jpg',
					bg:'white'},
			   {judul:"judul 56",
					deskripsi:"deskripsi 56",
					harga:"harga 56",
					gambar1:'kaos56.jpg',
					gambar2:'orang56.jpg',
					bg:'white'},
			   {judul:"judul 57",
					deskripsi:"deskripsi 57",
					harga:"harga 57",
					gambar1:'kaos57.jpg',
					gambar2:'orang57.jpg',
					bg:'white'},
			   {judul:"judul 58",
					deskripsi:"deskripsi 58",
					harga:"harga 58",
					gambar1:'kaos58.jpg',
					gambar2:'orang58.jpg',
					bg:'white'},
			   {judul:"judul 59",
					deskripsi:"deskripsi 59",
					harga:"harga 59",
					gambar1:'kaos59.jpg',
					gambar2:'orang59.jpg',
					bg:'white'},
			   {judul:"judul 60",
					deskripsi:"deskripsi 60",
					harga:"harga 60",
					gambar1:'kaos60.jpg',gambar2:'orang60.jpg',
					bg:'white'},
			   {judul:"judul 61",
					deskripsi:"deskripsi 61",
					harga:"harga 61",
					gambar1:'kaos61.jpg',
					gambar2:'orang61.jpg',
					bg:'white'},
			   {judul:"judul 62",
					deskripsi:"deskripsi 62",
					harga:"harga 62",
					gambar1:'kaos62.jpg',gambar2:'orangv2.jpg',
					bg:'white'},
			   {judul:"judul 63",
					deskripsi:"deskripsi 63",
					harga:"harga 63",
					gambar1:'kaos63.jpg',
					gambar2:'orang63.jpg',
					bg:'white'},
			   {judul:"judul 64",
					deskripsi:"deskripsi 64",
					harga:"harga 64",
					gambar1:'kaos64.jpg',
					gambar2:'orang64.jpg',
					bg:'white'},
			   {judul:"judul 65",
					deskripsi:"deskripsi 65",
					harga:"harga 65",
					gambar1:'kaos65.jpg',
					gambar2:'orang65.jpg',
					bg:'white'},
			   {judul:"judul 66",
					deskripsi:"deskripsi 66",
					harga:"harga 66",
					gambar1:'kaos66.jpg',
					gambar2:'orang66.jpg',
					bg:'white'},
			   {judul:"judul 67",
					deskripsi:"deskripsi 67",
					harga:"harga 67",
					gambar1:'kaos67.jpg',
					gambar2:'orang67.jpg',
					bg:'white'},
			   {judul:"judul 68",
					deskripsi:"deskripsi 68",
					harga:"harga 68",
					gambar1:'kaos68.jpg',
					gambar2:'orang68.jpg',
					bg:'white'},
			   {judul:"judul 69",
					deskripsi:"deskripsi 69",
					harga:"harga 69",
					gambar1:'kaos69.jpg',
					gambar2:'orang69.jpg',
					bg:'white'},
			   {judul:"judul 70",
					deskripsi:"deskripsi 70",
					harga:"harga 70",
					gambar1:'kaos70.jpg',
					gambar2:'orang70.jpg',
					bg:'white'},
			   {judul:"judul 71",
					deskripsi:"deskripsi 71",
					harga:"harga 71",
					gambar1:'kaos71.jpg',
					gambar2:'orang71.jpg',
					bg:'white'},
			   {judul:"judul 72",
					deskripsi:"deskripsi 72",
					harga:"harga 72",
					gambar1:'kaos72.jpg',
					gambar2:'orang72.jpg',
					bg:'white'},
			   {judul:"judul 73",
					deskripsi:"deskripsi 73",
					harga:"harga 73",
					gambar1:'kaos73.jpg',
					gambar2:'orang73.jpg',
					bg:'white'},
			   {judul:"judul 74",
					deskripsi:"deskripsi 74",
					harga:"harga 74",
					gambar1:'kaos74.jpg',
					gambar2:'orang74.jpg',
					bg:'white'},
			   {judul:"judul 75",
					deskripsi:"deskripsi 75",
					harga:"harga 75",
					gambar1:'kaos75.jpg',
					gambar2:'orang75.jpg',
					bg:'white'},
			   {judul:"judul 76",
					deskripsi:"deskripsi 76",
					harga:"harga 76",
					gambar1:'kaos76.jpg',
					gambar2:'orang76.jpg',
					bg:'white'},
			   {judul:"judul 77",
					deskripsi:"deskripsi 77",
					harga:"harga 77",
					gambar1:'kaos77.jpg',
					gambar2:'orang77.jpg',
					bg:'white'},
			   {judul:"judul 78",
					deskripsi:"deskripsi 78",
					harga:"harga 78",
					gambar1:'kaos78.jpg',
					gambar2:'orang78.jpg',
					bg:'white'},
			   {judul:"judul 79",
					deskripsi:"deskripsi 79",
					harga:"harga 79",
					gambar1:'kaos79.jpg',
					gambar2:'orang79.jpg',
					bg:'white'},
			   {judul:"judul 80",
					deskripsi:"deskripsi 80",
					harga:"harga 80",
					gambar1:'kaos80.jpg',
					gambar2:'orang80.jpg',
					bg:'white'},
			   {judul:"judul 81",
					deskripsi:"deskripsi 81",
					harga:"harga 81",
					gambar1:'kaos81.jpg',
					gambar2:'orang81.jpg',
					bg:'white'},
			   {judul:"judul 82",
					deskripsi:"deskripsi 82",
					harga:"harga 82",
					gambar1:'kaos82.jpg',
					gambar2:'orang82.jpg',
					bg:'white'},
			   {judul:"judul 83",
					deskripsi:"deskripsi 83",
					harga:"harga 83",
					gambar1:'kaos83.jpg',
					gambar2:'orang83.jpg',
					bg:'white'},
			   {judul:"judul 84",
					deskripsi:"deskripsi 84",
					harga:"harga 84",
					gambar1:'kaos84.jpg',
					gambar2:'orang84.jpg',
					bg:'white'},
			   {judul:"judul 85",
					deskripsi:"deskripsi 85",
					harga:"harga 85",
					gambar1:'kaos85.jpg',
					gambar2:'orang85.jpg',
					bg:'white'},
			   {judul:"judul 86",
					deskripsi:"deskripsi 86",
					harga:"harga 86",
					gambar1:'kaos86.jpg',
					gambar2:'orang86.jpg',
					bg:'white'},
			   {judul:"judul 87",
					deskripsi:"deskripsi 87",
					harga:"harga 87",
					gambar1:'kaos87.jpg',
					gambar2:'orang87.jpg'
					,bg:'white'},
			   {judul:"judul 88",
					deskripsi:"deskripsi 88",
					harga:"harga 88",
					gambar1:'kaos88.jpg',
					gambar2:'orang88.jpg',
					bg:'white'},
			   {judul:"judul 89",
					deskripsi:"deskripsi 89",
					harga:"harga 89",
					gambar1:'kaos89.jpg',
					gambar2:'orang89.jpg',
					bg:'white'},
			   {judul:"judul 90",
					deskripsi:"deskripsi 90",
					harga:"harga 90",
					gambar1:'kaos90.jpg',
					gambar2:'orang90.jpg',
					bg:'white'},
			   {judul:"judul 91",
					deskripsi:"deskripsi 91",
					harga:"harga 91",
					gambar1:'kaos91.jpg',
					gambar2:'orang91.jpg',
					bg:'white'},
			   {judul:"judul 92",
					deskripsi:"deskripsi 92",
					harga:"harga 92",
					gambar1:'kaos92.jpg',
					gambar2:'orang92.jpg',
					bg:'white'},
			   {judul:"judul 93",
					deskripsi:"deskripsi 93",
					harga:"harga 93",
					gambar1:'kaos93.jpg',
					gambar2:'orang93.jpg',
					bg:'white'},
			   {judul:"judul 94",
					deskripsi:"deskripsi 94",
					harga:"harga 94",
					gambar1:'kaos94.jpg',
					gambar2:'orang94.jpg',
					bg:'white'},
			   {judul:"judul 95",
					deskripsi:"deskripsi 95",
					harga:"harga 95",
					gambar1:'kaos95.jpg',
					gambar2:'orang95.jpg',
					bg:'white'},
			   {judul:"judul 96",
					deskripsi:"deskripsi 96",
					harga:"harga 96",
					gambar1:'kaos96.jpg',
					gambar2:'orang96.jpg',
					bg:'white'},
			   {judul:"judul 97",
					deskripsi:"deskripsi 97",
					harga:"harga 97",
					gambar1:'kaos97.jpg',
					gambar2:'orang97.jpg',
					bg:'white'},
			   {judul:"judul 98",
					deskripsi:"deskripsi 98",
					harga:"harga 98",
					gambar1:'kaos98.jpg',
					gambar2:'orang98.jpg',
					bg:'white'},
			   {judul:"judul 99",
					deskripsi:"deskripsi 99",
					harga:"harga 99",
					gambar1:'kaos99.jpg',
					gambar2:'orang99.jpg',
					bg:'white'},
			   {judul:"judul 100",
					deskripsi:"deskripsi 100",
					harga:"harga 100",
					gambar1:'kaos100.jpg',
					gambar2:'orang100.jpg',
					bg:'white'},
			   {judul:"judul 101",
					deskripsi:"deskripsi 101",
					harga:"harga 101",
					gambar1:'kaos101.jpg',
					gambar2:'orang101.jpg',
					bg:'white'},
			   {judul:"judul 102",
					deskripsi:"deskripsi 102",
					harga:"harga 102",
					gambar1:'kaos102.jpg',
					gambar2:'orang102.jpg',bg:'white'},
			   {judul:"judul 103",
					deskripsi:"deskripsi 103",
					harga:"harga 103",
					gambar1:'kaos103.jpg',
					gambar2:'orang103.jpg',
					bg:'white'},
			   {judul:"judul 104",
					deskripsi:"deskripsi 104",
					harga:"harga 104",
					gambar1:'kaos104.jpg',
					gambar2:'orang104.jpg',
					bg:'white'},
			   {judul:"judul 105",
					deskripsi:"deskripsi 105",
					harga:"harga 105",
					gambar1:'kaos105.jpg',
					gambar2:'orang105.jpg',
					bg:'white'},
			   {judul:"judul 106",
					deskripsi:"deskripsi 106",
					harga:"harga 106",
					gambar1:'kaos106.jpg',
					gambar2:'orang106.jpg',
					bg:'white'}
			  ]
			 ]